name: "CI: Build Test"

on: [push, pull_request]

env:
  QT_VERSION: 5.15.2

jobs:
  build:
    name: "${{ matrix.config.os }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            binary: Release/cpeditor.exe
          - os: ubuntu-latest
            binary: cpeditor
          - os: macos-latest
            binary: cpeditor.app/Contents/MacOS/cpeditor

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Qt environment
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          version: ${{ env.QT_VERSION }}

      - name: "[Linux] Download clang-tidy"
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install clang-tidy-14
          sudo ln -s "$(which clang-tidy-14)" "/usr/local/bin/clang-tidy"

      - name: "[macOS] Download clang-tidy"
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew install llvm
          ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"

      # https://www.blumia.net/2020/07/31/Setting-Up-KDE-Craft-CI-Environment-Manually-Under-Windows.html
      - name: "[Windows] Download KTextEditor"
        if: startsWith(matrix.config.os, 'windows')
        run: |
          git clone https://github.com/KDE/craftmaster.git C:\CraftMaster
          function craft() {
            & python "C:\CraftMaster\CraftMaster.py" --config .craft-master.ini --target win64_msvc2019_64 -c $args
            if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
          }
          craft craft
          craft ktexteditor

      - name: "[Linux] Download KTextEditor"
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          sudo apt-get install extra-cmake-modules libkf5texteditor-dev

      - name: "[macOS] Download KTextEditor"
        if: startsWith(matrix.config.os, 'macos')
        run: |
          brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git --force-auto-update
          brew install kde-mac/kde/kf5-ktexteditor

      - name: "[Unix] Build"
        if: startsWith(matrix.config.os, 'ubuntu') || startsWith(matrix.config.os, 'macos')
        run: |
          cmake -B build -S . -D USE_CLANG_TIDY=On -D CMAKE_BUILD_TYPE=Release
          cmake --build build -j4

      - name: "[Windows] Build"
        if: startsWith(matrix.config.os, 'windows')
        run: |
          $env:Path="$env:Path;C:/CraftRoot/bin;C:/CraftRoot/dev-utils/bin;C:/CraftRoot/msys/mingw64/bin"
          cmake -B build -S . -D USE_CLANG_TIDY=On
          cmake --build build -j4 --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "cpeditor-${{ matrix.config.os }}-${{ github.run_id }}"
          path: build/${{ matrix.config.binary }}
