name: "Update Snap"

on:
  push:
  workflow_dispatch:

jobs:
  snap:
    name: "Update Snap"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update Snapcraft
        run: |
          cp dist/snap/snapcraft.yaml snapcraft.yaml

      - uses: snapcore/action-build@v1
        id: build

      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
